# ===== ESTÁGIO 1: Build da Aplicação com Maven (Java 21) =====
FROM maven:3.9.6-eclipse-temurin-21 AS builder

WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline
COPY src ./src
RUN mvn clean package -DskipTests


# ===== ESTÁGIO 2: Runtime da Aplicação (Java 21) =====
FROM eclipse-temurin:21-jre

WORKDIR /app
EXPOSE 8080
COPY --from=builder /app/target/*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]